### ISSUE TITLE
Progress and contributing

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [ubports-oneplus6/documentation#11]
Does anyone have an estimate on when we might see a newer image or OTA integration of the OnePlus 6T?
Is there a road map of what needs to be done and how to help?
Where is the work being done?
Can we follow the progress somewhere?
How can we help to get the device page on ubports.com to reflect the current state of the device?
What is needed to get it added to the installer?
Can I compile a newer GSI for the 6T and if yes where is the code and are there instructions?

**Comment by MrCyjaneK** [comment]
Ota is already done, for gsi ubports-gsi organization hold some out of date forked repo
