### ISSUE TITLE
Armhf libs on aarch64 

### ISSUE THREAD

**Issue by Intrinsically-Sublime** [ubports-oneplus6/documentation#12]
While trying to install Arm64 click package on the 6T using the UT tweak tool, click via the command line or pkcon via the command line arm64 apps fail to install.

While using pkcon and allowing untrusted it then reports 
```
Package architecture "arm64" not compatible with system architecture "armhf"
```
, but if you run "arch" or "uname -a" on the command line it reports the phone being aarch64.

If I search the phone for directories containing aarch64 folders I get 0
If I search the phone for directories containing arm64 folders I get 2
```
/sys/module/kyro3xx_arm64_edac
/android/vendor/app/Rftoolkit/lib/arm6
```
If I search the phone for directories containing gnueabihf I get 24 like these examples
```
/usr/lib/arm-linux-gnueabihf/
/usr/lib/gcc/arm-linux-gnueabihf/
/usr/share/click/preinstalled/com.ubuntu.camera/3.1.3/lib/arm-linux-gnueabihf
```
Plus every other preinstalled app and working app I have installed. Since they are all armhf libs I think we are looking at an armhf file system on an arm64 device.

Am I misunderstanding this or was this a quick way of getting a working image or some other reason

**Comment by MrCyjaneK** [comment]
Closing, GSI was armhf.
