### ISSUE TITLE
op6t screen turns off and doesnt turn back on

### ISSUE THREAD

**Issue by Nima0003** [ubports-oneplus6/documentation#13]
I saw a similar issue but I would like to provide more details.

I tried to use the brightness slider and the screen turned off.

If I leave it it'll turn back on after exactly 1 minute, but if I touch the screen or any button, it'll turn back off. 

I tried rebooting obviously and even tried to bring the slider back up in the few seconds that the screen functions while freshly booted, but no luck.

**Comment by MrCyjaneK** [comment]
It is fixed in newer release of GSI: https://build.lolinet.com/file/halium/GSI/ubports_GSI_installer_v10.zip

Just flash it on top of current system

**Comment by u8l-git** [comment]
> It is fixed in newer release of GSI: https://build.lolinet.com/file/halium/GSI/ubports_GSI_installer_v10.zip
> 
> Just flash it on top of current system

The link to the GSI is longer available.

**Comment by MrCyjaneK** [comment]
Noticed, @erfanoabdi probably deleted it.
