### ISSUE TITLE
Links to Stock ROM in README.md are broken

### ISSUE THREAD

**Issue by magdesign** [ubports-oneplus6/documentation#14]
Thanks for this guide!

The links to the ROMs in README are not working anymore, a search in the Internet gave me following links:

oneplus 6 [official build 10.3.x](https://www.oneplus.com/support/softwareupgrade/details?code=PM1574156173727)

oneplus 6 Android 9 ROMs found [here:](https://www.getdroidtips.com/download-oxygenos-9-0-9-9-0-17-update-for-oneplus-6-and-6t/)
OnePlus 6 OxygenOS 9.0.9 | [Download](https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus6Oxygen/OnePlus6Oxygen_22.O.34_GLO_034_1909112343/OnePlus6Oxygen_22_OTA_034_all_1909112343_dd26.zip)
OnePlus 6T OxygenOS 9.0.17 | [Download](https://otafsg1.h2os.com/patch/amazone2/GLO/OnePlus6TOxygen/OnePlus6TOxygen_34.O.24_GLO_024_1909112343/OnePlus6TOxygen_34_OTA_024_all_1909112343_d5b1905.zip)

and the Android 9 rollback firmware is found [here](https://forum.xda-developers.com/t/guide-rollback-downgrade-from-oos-android-10-q-to-stable-9-pie.4000645/)

**Edit:**

Download the rollback firmware, push it to the phone with:
`adb push 'fulldowngrade_wipe_MSM_17819_181025_2315_user_MP1_release.zip' /sdcard`

Go to Settings > System > System Updates
Push the Gear icon followed by 'Local upgrade'
Select the fulldowngrade package
Confirm
Wait until finished
Reboot (takes a while with spinning circle logo)
Enable developer mode
Enable USB debugging
Use UBPorts installer to flash...

**Edit2:**

To recover back to Android/or install Android9 via terminal:

Download [TWRP3.3.1](https://dl.twrp.me/enchilada/twrp-3.3.1-2-enchilada.img.html)
newer versions of TWRP did not work for me, but you might test and give feedback...

flash it with:
`fastboot boot 'twrp-3.3.1-2-enchilada.img' `

Download original [Oxygen Android 9 ROM](https://otafsg.h2os.com/patch/amazone2/GLO/OnePlus6Oxygen/OnePlus6Oxygen_22.O.25_GLO_025_1809150101/OnePlus6Oxygen_22_OTA_025_all_1809150101_35981ba3cecc19e.zip)

push this image to the device with:
`
adb push OnePlus6Oxygen_22_OTA_025_all_1809150101_35981ba3cecc19e.zip /sdcard`

in TWRP on the phone select: INSTALL and there select the pushed .zip file
this might take quite a while...

Now you are ready to use Android (first boot takes ages...) or to start installing UBports again.

BTW:
pw is: phablet

**Comment by svenha** [comment]
Has anybody tried this for the McLaren edition? I guess the 6T version would be the more promising candidate?

**Comment by SrvClick** [comment]
https://www.mediafire.com/file/90oatr7nz8li9ej/Fulldowngrade_wipe_18801_181024_2027_user_MP2_release.zip/file

**Comment by magdesign** [comment]
[fulldowngrade_wipe_MSM_17819_181025_2315_user_MP1_release](https://mega.nz/file/ouJxBCbA#lNuppILlN9NluH6S2Vo1d_kIL5JGXkzIYBbJSG5HeX8)
