### ISSUE TITLE
Low volume on built-in speaker

### ISSUE THREAD

**Issue by tomoqv** [ubports-oneplus6/documentation#3]
The volume on OP6 is very very low. I have tried uVolman to amplify it, but it is still really low. Headphone volume is loud though. I don't know if this is a software issue or if it has to do with the hardware.

**Comment by MrCyjaneK** [comment]
Hey @tomoqv I didn't have this issue, what app have you used to check it? Was it some youtube video or mp3 from music app?

**Comment by tomoqv** [comment]
> Hey @tomoqv I didn't have this issue, what app have you used to check it? Was it some youtube video or mp3 from music app?

Sorry, should have withdrawn this. After a full restart (power off/power off), the issue went away. Before, the sound was barely hearable at max volume. Now everything appears to be fine.

Thanks,
Tomas

**Comment by MrCyjaneK** [comment]
> 
> Sorry, should have withdrawn this. After a full restart (power off/power off), the issue went away. Before, the sound was barely hearable at max volume. Now everything appears to be fine.
> 
> Thanks,
> Tomas

This issue occurs sometimes, either by finishing a call or when music app crashes, the device is setting the volume of, for example, incall audio while it should set music volume.
