### ISSUE TITLE
Flashlight option isn't present in the GUI

### ISSUE THREAD

**Issue by dominichayesferen** [ubports-oneplus6/documentation#6]
In short, the option to turn on the flashlight isn't present in the GUI, when I've heard rumblings that it should be displayed in the Battery indicator's menu as a toggle. The flashlight does work when used in the Camera application.

(OnePlus 6)

**Comment by MrCyjaneK** [comment]
https://open-store.io/app/com.ubuntu.developer.majster-pl.utorch
https://open-store.io/app/indicator-torch.nfsprodriver
