### ISSUE TITLE
With Anbox installed the system never seems to finish shutting down / rebooting

### ISSUE THREAD

**Issue by dominichayesferen** [ubports-oneplus6/documentation#7]
When rebooting or shutting down UBPorts before Anbox is installed via the OnePlus 5 documentation, it seems to successfully do so in due time, however when Anbox is installed the system seems to get stuck on the black screen it displays when shutting down or rebooting and never successfully does said operation.

(OnePlus 6)

**Comment by kcxt** [comment]
Please SSH to the device and run `dmesg -w` while shutting it down, include the log.

**Comment by dominichayesferen** [comment]
@calebccff https://paste.ubuntu.com/p/YdC7ptJMGw/

**Comment by dominichayesferen** [comment]
Interestingly a second reboot command via ssh makes it instantly restart.

**Comment by MrCyjaneK** [comment]
Waydroid works well.
