### ISSUE TITLE
USSD codes error.

### ISSUE THREAD

**Issue by SevralTi** [ubports-oneplus6/documentation#9]
If I trying to execute USSD code on my phoen with Ubuntu Touch, I am getting stuck on loading screen.

**Comment by MrCyjaneK** [comment]
I can confirm that this issue exists.

**Comment by MrCyjaneK** [comment]
It is fixed in newer release of GSI: https://build.lolinet.com/file/halium/GSI/ubports_GSI_installer_v10.zip
